// <auto-generated />
using System;
using Dự_án_Alta_Software.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dự_án_Alta_Software.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Dự_án_Alta_Software.Model.BaiKiemTra", b =>
                {
                    b.Property<int>("id_baikiemtra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_baikiemtra"), 1L, 1);

                    b.Property<int>("LoaiBaiKiemTraid_loaibaikiemtra")
                        .HasColumnType("int");

                    b.Property<string>("bailam")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("giangvien")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("lich")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ngaylambai")
                        .HasColumnType("datetime2");

                    b.Property<string>("noidungkiemtra")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("tenmon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("thoigian")
                        .HasColumnType("datetime2");

                    b.Property<string>("tinhtrang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id_baikiemtra");

                    b.HasIndex("LoaiBaiKiemTraid_loaibaikiemtra");

                    b.ToTable("BaiKiemTra");
                });

            modelBuilder.Entity("Dự_án_Alta_Software.Model.ChiTietLopHoc", b =>
                {
                    b.Property<int>("LopHocid_lophoc")
                        .HasColumnType("int");

                    b.Property<int>("lopchuahoanthanh")
                        .HasColumnType("int");

                    b.Property<int>("lopdahoanthanh")
                        .HasColumnType("int");

                    b.Property<string>("lopsapmo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasIndex("LopHocid_lophoc");

                    b.ToTable("ChiTietLopHoc");
                });

            modelBuilder.Entity("Dự_án_Alta_Software.Model.Diem", b =>
                {
                    b.Property<int>("id_diem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_diem"), 1L, 1);

                    b.Property<int>("MonHocid_monhoc")
                        .HasColumnType("int");

                    b.Property<string>("danhgia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("diemchuyencan")
                        .HasColumnType("float");

                    b.Property<double>("diemtongket")
                        .HasColumnType("float");

                    b.Property<double>("diemtrungbinh")
                        .HasColumnType("float");

                    b.Property<double>("heso2")
                        .HasColumnType("float");

                    b.Property<double>("heso3")
                        .HasColumnType("float");

                    b.Property<string>("ketqua")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("kiemtramieng")
                        .HasColumnType("float");

                    b.Property<DateTime>("ngaycapnhat")
                        .HasColumnType("datetime2");

                    b.Property<string>("tengiangvien")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("tenmonhoc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id_diem");

                    b.HasIndex("MonHocid_monhoc");

                    b.ToTable("Diem");
                });

            modelBuilder.Entity("Dự_án_Alta_Software.Model.GiangVien", b =>
                {
                    b.Property<int>("id_giangvien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_giangvien"), 1L, 1);

                    b.Property<int>("TaiKhoanid_taikhoan")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sdt")
                        .HasColumnType("int");

                    b.Property<string>("tengiangvien")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id_giangvien");

                    b.HasIndex("TaiKhoanid_taikhoan");

                    b.ToTable("GiangVien");
                });

            modelBuilder.Entity("Dự_án_Alta_Software.Model.HocSinh", b =>
                {
                    b.Property<int>("id_hocsinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_hocsinh"), 1L, 1);

                    b.Property<int>("TaiKhoanid_taikhoan")
                        .HasColumnType("int");

                    b.Property<string>("diachi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("hoten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("namsinh")
                        .HasColumnType("datetime2");

                    b.Property<int>("sdt")
                        .HasColumnType("int");

                    b.HasKey("id_hocsinh");

                    b.HasIndex("TaiKhoanid_taikhoan");

                    b.ToTable("HocSinh");
                });

            modelBuilder.Entity("Dự_án_Alta_Software.Model.KhoaHoc", b =>
                {
                    b.Property<int>("id_khoahoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_khoahoc"), 1L, 1);

                    b.Property<int>("LopHocid_lophoc")
                        .HasColumnType("int");

                    b.Property<int>("TaiKhoanid_taikhoan")
                        .HasColumnType("int");

                    b.Property<int>("hocky")
                        .HasColumnType("int");

                    b.Property<DateTime>("ngaybatdau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngayketthuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("tenkhoahoc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id_khoahoc");

                    b.HasIndex("LopHocid_lophoc");

                    b.HasIndex("TaiKhoanid_taikhoan");

                    b.ToTable("KhoaHoc");
                });

            modelBuilder.Entity("Dự_án_Alta_Software.Model.KhoiLop", b =>
                {
                    b.Property<int>("id_khoilop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_khoilop"), 1L, 1);

                    b.Property<int>("LopHocid_lophoc")
                        .HasColumnType("int");

                    b.Property<string>("tenkhoi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id_khoilop");

                    b.HasIndex("LopHocid_lophoc");

                    b.ToTable("KhoiLop");
                });

            modelBuilder.Entity("Dự_án_Alta_Software.Model.LoaiBaiKiemTra", b =>
                {
                    b.Property<int>("id_loaibaikiemtra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_loaibaikiemtra"), 1L, 1);

                    b.Property<string>("baichuahoanthanh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("baidahoanthanh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("baikiemtrasaptoi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("tenloai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id_loaibaikiemtra");

                    b.ToTable("LoaiBaiKiemTra");
                });

            modelBuilder.Entity("Dự_án_Alta_Software.Model.LoaiTaiLieu", b =>
                {
                    b.Property<int>("id_loaitailieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_loaitailieu"), 1L, 1);

                    b.Property<int>("TaiLieuid_tailieu")
                        .HasColumnType("int");

                    b.Property<int>("soluong")
                        .HasColumnType("int");

                    b.Property<string>("tentailieu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id_loaitailieu");

                    b.HasIndex("TaiLieuid_tailieu");

                    b.ToTable("LoaiTaiLieu");
                });

            modelBuilder.Entity("Dự_án_Alta_Software.Model.LopHoc", b =>
                {
                    b.Property<int>("id_lophoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_lophoc"), 1L, 1);

                    b.Property<int>("MonHocid_monhoc")
                        .HasColumnType("int");

                    b.Property<string>("chude")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("giangvien")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("link_online")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("matkhau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("monhoc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("tenlophoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("thoigian")
                        .HasColumnType("datetime2");

                    b.Property<string>("trangthai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id_lophoc");

                    b.HasIndex("MonHocid_monhoc");

                    b.ToTable("LopHoc");
                });

            modelBuilder.Entity("Dự_án_Alta_Software.Model.MonHoc", b =>
                {
                    b.Property<int>("id_monhoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_monhoc"), 1L, 1);

                    b.Property<int>("BaiKiemTraid_baikiemtra")
                        .HasColumnType("int");

                    b.Property<string>("tenmonhoc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id_monhoc");

                    b.HasIndex("BaiKiemTraid_baikiemtra");

                    b.ToTable("MonHoc");
                });

            modelBuilder.Entity("Dự_án_Alta_Software.Model.PhanCong", b =>
                {
                    b.Property<int>("id_phancong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_phancong"), 1L, 1);

                    b.Property<int>("GiangVienid_giangvien")
                        .HasColumnType("int");

                    b.Property<int>("sotiet")
                        .HasColumnType("int");

                    b.Property<string>("tenbang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("thoigian")
                        .HasColumnType("datetime2");

                    b.HasKey("id_phancong");

                    b.HasIndex("GiangVienid_giangvien");

                    b.ToTable("PhanCong");
                });

            modelBuilder.Entity("Dự_án_Alta_Software.Model.PhanQuyen", b =>
                {
                    b.Property<int>("id_quyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_quyen"), 1L, 1);

                    b.Property<string>("tenquyen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id_quyen");

                    b.ToTable("PhanQuyen");
                });

            modelBuilder.Entity("Dự_án_Alta_Software.Model.TaiKhoan", b =>
                {
                    b.Property<int>("id_taikhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_taikhoan"), 1L, 1);

                    b.Property<int>("PhanQuyenid_quyen")
                        .HasColumnType("int");

                    b.Property<string>("matkhau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("tentaikhoan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id_taikhoan");

                    b.HasIndex("PhanQuyenid_quyen");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("Dự_án_Alta_Software.Model.TaiLieu", b =>
                {
                    b.Property<int>("id_tailieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_tailieu"), 1L, 1);

                    b.Property<int>("GiangVienid_giangvien")
                        .HasColumnType("int");

                    b.Property<string>("nguoibiensoan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("noidung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sotrang")
                        .HasColumnType("int");

                    b.Property<string>("tentailieu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id_tailieu");

                    b.HasIndex("GiangVienid_giangvien");

                    b.ToTable("TaiLieu");
                });

            modelBuilder.Entity("Dự_án_Alta_Software.Model.BaiKiemTra", b =>
                {
                    b.HasOne("Dự_án_Alta_Software.Model.LoaiBaiKiemTra", "LoaiBaiKiemTra")
                        .WithMany()
                        .HasForeignKey("LoaiBaiKiemTraid_loaibaikiemtra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiBaiKiemTra");
                });

            modelBuilder.Entity("Dự_án_Alta_Software.Model.ChiTietLopHoc", b =>
                {
                    b.HasOne("Dự_án_Alta_Software.Model.LopHoc", "LopHoc")
                        .WithMany()
                        .HasForeignKey("LopHocid_lophoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("Dự_án_Alta_Software.Model.Diem", b =>
                {
                    b.HasOne("Dự_án_Alta_Software.Model.MonHoc", "MonHoc")
                        .WithMany()
                        .HasForeignKey("MonHocid_monhoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("Dự_án_Alta_Software.Model.GiangVien", b =>
                {
                    b.HasOne("Dự_án_Alta_Software.Model.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanid_taikhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("Dự_án_Alta_Software.Model.HocSinh", b =>
                {
                    b.HasOne("Dự_án_Alta_Software.Model.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanid_taikhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("Dự_án_Alta_Software.Model.KhoaHoc", b =>
                {
                    b.HasOne("Dự_án_Alta_Software.Model.LopHoc", "LopHoc")
                        .WithMany()
                        .HasForeignKey("LopHocid_lophoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dự_án_Alta_Software.Model.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanid_taikhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopHoc");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("Dự_án_Alta_Software.Model.KhoiLop", b =>
                {
                    b.HasOne("Dự_án_Alta_Software.Model.LopHoc", "LopHoc")
                        .WithMany()
                        .HasForeignKey("LopHocid_lophoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("Dự_án_Alta_Software.Model.LoaiTaiLieu", b =>
                {
                    b.HasOne("Dự_án_Alta_Software.Model.TaiLieu", "TaiLieu")
                        .WithMany()
                        .HasForeignKey("TaiLieuid_tailieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiLieu");
                });

            modelBuilder.Entity("Dự_án_Alta_Software.Model.LopHoc", b =>
                {
                    b.HasOne("Dự_án_Alta_Software.Model.MonHoc", "MonHoc")
                        .WithMany()
                        .HasForeignKey("MonHocid_monhoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("Dự_án_Alta_Software.Model.MonHoc", b =>
                {
                    b.HasOne("Dự_án_Alta_Software.Model.BaiKiemTra", "BaiKiemTra")
                        .WithMany()
                        .HasForeignKey("BaiKiemTraid_baikiemtra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaiKiemTra");
                });

            modelBuilder.Entity("Dự_án_Alta_Software.Model.PhanCong", b =>
                {
                    b.HasOne("Dự_án_Alta_Software.Model.GiangVien", "GiangVien")
                        .WithMany()
                        .HasForeignKey("GiangVienid_giangvien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiangVien");
                });

            modelBuilder.Entity("Dự_án_Alta_Software.Model.TaiKhoan", b =>
                {
                    b.HasOne("Dự_án_Alta_Software.Model.PhanQuyen", "PhanQuyen")
                        .WithMany()
                        .HasForeignKey("PhanQuyenid_quyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhanQuyen");
                });

            modelBuilder.Entity("Dự_án_Alta_Software.Model.TaiLieu", b =>
                {
                    b.HasOne("Dự_án_Alta_Software.Model.GiangVien", "GiangVien")
                        .WithMany()
                        .HasForeignKey("GiangVienid_giangvien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiangVien");
                });
#pragma warning restore 612, 618
        }
    }
}
